# Generated by Django 4.1.6 on 2023-02-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('set', models.CharField(max_length=100)),
                ('year_manufactured', models.IntegerField()),
                ('features', models.TextField(max_length=250)),
            ],
        ),
    ]
