# Generated by Django 4.1.6 on 2023-02-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_cover_alter_cleaning_options_alter_cleaning_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
